version: '3.4'

services:
  db: 
    image: restwithnet8api-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build: 
        context: .
        dockerfile: db/Dockerfile
    environment: 
        TZ: America/Sao_Paulo
        MYSQL_ROOT_PASSWORD: docker
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
        MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
        - 3308:3306
    networks:
        - udemy-network

  restwithnet8.api:
    image: restwithnet8api
    build:
      context: .
      dockerfile: RestWithNet8.Api/Dockerfile
    environment:
        TZ: America/Sao_Paulo
        ASPNETCORE_ENVIROMENT: Development
    ports:
        - 44300:8081
        - 4430:8080
    depends_on: 
        - db
    networks:
        - udemy-network

networks:
    udemy-network: 
      driver: bridge
  
